#!/usr/bin/env bash

help() {
  printf "=======================================================================\n"
  printf "\033[0;32mAWS-SSH: Connect to AWS EC2 Instances at Lightning Speed\033[0m \n"
  printf "=======================================================================\n\n"
  printf "Usage: \n"
  printf "\033[0;31mList Instances\033[0m:\taws-ssh list \033[0;36m<partial-search-term>\033[0m \n"
  printf "\033[0;31mConnect\033[0m:\taws-ssh connect \033[0;36m<instance-name-search-term> <username>\033[0m \n\n"
  printf "Notes: \n"
  printf "\033[0;36m<username>\033[0m will be used from \033[0;36m~/.aws-ssh-config\033[0m if not provided \n"
  printf "\033[0;36mBastion Servers\033[0m can be configured in \033[0;36m~/.aws-ssh-config\033[0m \n"
  printf "\033[0;36mPrivate Keys (*.pem)\033[0m can be configured in \033[0;36m~/.aws-ssh-config\033[0m \n"
  printf "\nExample \033[0;36m~/.aws-ssh-config\033[0m:\n\n"
  printf " \`\`\`\n"
  printf " \e[3mPRIVATE_KEY=~/.ssh/somekey.pem\e[0m \n"
  printf " \e[3mBASTION=username@192.168.50.100\e[0m\n"
  printf " \e[3mDEFAULT_USER=ec2-user\e[0m \n\n"
  printf " \`\`\`\n"
}

load-config() {
  [ -f "$HOME/.aws-ssh-config" ] && source "$HOME/.aws-ssh-config"
  [ -f "$HOME/.config/aws-ssh/config" ] && source "$HOME/.config/aws-ssh/config"
  [ -f "$XDG_CONFIG_PATH/.aws-ssh/config" ] && source "$XDG_CONFIG_PATH/.aws-ssh/config"
}

bastion() {
  ([ ! -z $BASTION ] && echo "-J $BASTION") || echo ""
}

private-key-specifier() {
  ([ ! -z $PRIVATE_KEY ] && echo "-i $PRIVATE_KEY") || echo ""
}

default-user() {
  [ -z "$1" ] && echo "$DEFAULT_USER" || echo "$1"
}

aws-instances() {
  AWS_FILTER="*"
  OUTPUT_TYPE="table"
  [ ! -z "$1" ] && AWS_FILTER="*$1*"
  [ ! -z "$2" ] && OUTPUT_TYPE="$2"
  aws ec2 describe-instances\
    --query "Reservations[*].Instances[*].{InstanceID:InstanceId,PrivateIP:PrivateIpAddress,PublicIPAddr:PublicIp,Instance:Tags[?Key=='Name']|[0].Value}"\
    --filter "Name=tag:Name,Values=$AWS_FILTER"\
    --output "$OUTPUT_TYPE" 
}

aws-connect(){
  [ -z "$1" ] && help && return
  CONN_IP_ADDR="$(echo "$(aws-instances $1 json | jq -r '.[] | .[] | "\(.PrivateIP)\t\(.Instance)\t\(.InstanceID)\t\(.PublicIPAddr)"')" | fzf | awk '{print $1}')"
  ssh $(bastion) $(private-key-specifier) "$(default-user $2)@$CONN_IP_ADDR"
}

initialize() {
  load-config
  case "$1" in
    list)
      aws-instances $2
      ;;
    connect)
      aws-connect ${@:2}
      ;;
    *)
      help
      ;;
  esac
}

initialize $@
